In [1]:
from google.colab import drive
drive.mount('/content/grdive')

Go to this URL in a browser: https://accounts.google.com/o/oauth2/auth?client_id=947318989803-6bn6qk8qdgf4n4g3pfee6491hc0brc4i.apps.googleusercontent.com&redirect_uri=urn%3Aietf%3Awg%3Aoauth%3A2.0%3Aoob&scope=email%20https%3A%2F%2Fwww.googleapis.com%2Fauth%2Fdocs.test%20https%3A%2F%2Fwww.googleapis.com%2Fauth%2Fdrive%20https%3A%2F%2Fwww.googleapis.com%2Fauth%2Fdrive.photos.readonly%20https%3A%2F%2Fwww.googleapis.com%2Fauth%2Fpeopleapi.readonly&response_type=code

Enter your authorization code:
··········
Mounted at /content/grdive


In [0]:
import pandas as pd
import numpy as np
import math 
from collections import deque
from numpy import array
import random
import datetime
import calendar
import time
from sklearn.impute import SimpleImputer
from sklearn.preprocessing import LabelEncoder,OneHotEncoder
import datetime as dt
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.linear_model import LinearRegression
import statsmodels.api as sm
from sklearn.tree import DecisionTreeRegressor
from sklearn.ensemble import RandomForestRegressor

In [0]:
#dfStore =pd.read_csv('/content/grdive/My Drive/Rossman Machine Learning/store.csv')

In [4]:
#dfTrain =pd.read_csv('/content/grdive/My Drive/Rossman Machine Learning/train.csv')

/usr/local/lib/python3.6/dist-packages/IPython/core/interactiveshell.py:2718: DtypeWarning: Columns (7) have mixed types. Specify dtype option on import or set low_memory=False.
  interactivity=interactivity, compiler=compiler, result=result)


In [102]:
#dfTrain =pd.read_csv('/content/grdive/My Drive/Rossman Machine Learning/completeData.csv')

/usr/local/lib/python3.6/dist-packages/IPython/core/interactiveshell.py:2718: DtypeWarning: Columns (8) have mixed types. Specify dtype option on import or set low_memory=False.
  interactivity=interactivity, compiler=compiler, result=result)


In [0]:
dfTrain =pd.read_csv('/content/grdive/My Drive/Rossman Machine Learning/CompleteDataFinal.csv')

In [6]:
print(dfTrain.head())

   Unnamed: 0  Store  DayOfWeek   Date  Sales  ...  PI2  PI3  SH11  SH2  SH3
0           0      1          5  16647   5263  ...    0    0     1    0    0
1           1      2          5  16647   6064  ...    1    0     1    0    0
2           2      3          5  16647   8314  ...    1    0     1    0    0
3           3      4          5  16647  13995  ...    0    0     1    0    0
4           4      5          5  16647   4822  ...    0    0     1    0    0

[5 rows x 26 columns]


In [0]:
dfTrain=dfTrain.iloc[:,1:]

In [0]:
'''
dfTrain["StoreType"] = np.nan
dfTrain["Assortment"] = np.nan
dfTrain["CompetitionDistance"] = np.nan
dfTrain["CompetitionOpenSinceMonth"] = np.nan
dfTrain["CompetitionOpenSinceYear"] = np.nan
dfTrain["Promo2"] = np.nan
dfTrain["Promo2SinceWeek"] = np.nan
dfTrain["Promo2SinceYear"] = np.nan
dfTrain["PromoInterval"] = np.nan
'''

In [0]:
'''
for i in range(1,20):   #store value from 1 to 50 stores
  matches = dfTrain[dfTrain['Store'] ==i].index.tolist()
  for j in matches:  #matched index
    
    dfTrain.loc[j,['StoreType']] =  (dfStore.loc[dfStore.Store==i]['StoreType'][i-1])
    dfTrain.loc[j,['Assortment']] =  (dfStore.loc[dfStore.Store==i]['Assortment'][i-1])
    dfTrain.loc[j,['CompetitionDistance']] =  (dfStore.loc[dfStore.Store==i]['CompetitionDistance'][i-1])
    dfTrain.loc[j,['CompetitionOpenSinceMonth']] =  (dfStore.loc[dfStore.Store==i]['CompetitionOpenSinceMonth'][i-1])
    dfTrain.loc[j,['CompetitionOpenSinceYear']] =  (dfStore.loc[dfStore.Store==i]['CompetitionOpenSinceYear'][i-1])
    dfTrain.loc[j,['Promo2']] =  (dfStore.loc[dfStore.Store==i]['Promo2'][i-1])
    dfTrain.loc[j,['Promo2SinceWeek']] =  (dfStore.loc[dfStore.Store==i]['Promo2SinceWeek'][i-1])
    dfTrain.loc[j,['Promo2SinceYear']] =  (dfStore.loc[dfStore.Store==i]['Promo2SinceYear'][i-1])
    dfTrain.loc[j,['PromoInterval']] =  (dfStore.loc[dfStore.Store==i]['PromoInterval'][i-1])
    
    print("j is "+str(j))
    
    
  print("Store "+str(i)+" is done!!!")
  '''
    


In [0]:
#dfTrain.to_csv('completeData.csv')

In [0]:
'''
dfTrain.iloc[:,9].fillna('u1', inplace=True)
dfTrain.iloc[:,10].fillna('u2', inplace=True)
dfTrain.iloc[:,11].fillna(0, inplace=True)
dfTrain.iloc[:,12].fillna(0, inplace=True)
dfTrain.iloc[:,13].fillna(0, inplace=True)
dfTrain.iloc[:,14].fillna(0, inplace=True)
dfTrain.iloc[:,15].fillna(0, inplace=True)
dfTrain.iloc[:,16].fillna(0, inplace=True)
dfTrain.iloc[:,17].fillna('Not Applicable', inplace=True)
'''

In [0]:
'''
dummies_storeType=pd.get_dummies(dfTrain['StoreType'])

dfTrain=pd.concat([dfTrain,dummies_storeType],axis='columns')

dfTrain = dfTrain.rename({'a': 'ST1', 'c': 'ST2','d':'ST3','u1':'ST4'}, axis=1) 

dummies_assortment=pd.get_dummies(dfTrain['Assortment'])

dummies_promoInterval=pd.get_dummies(dfTrain['PromoInterval'])

dfTrain=pd.concat([dfTrain,dummies_assortment,dummies_promoInterval],axis='columns')

dfTrain = dfTrain.rename({'a': 'AT1', 'c': 'AT2','u2':'AT3'}, axis=1) 

dfTrain = dfTrain.rename({'Feb,May,Aug,Nov': 'PI1', 'Jan,Apr,Jul,Oct': 'PI2','Mar,Jun,Sept,Dec':'PI3','Not Applicable':'PI4'}, axis=1) 

dfTrain=dfTrain.drop(['StoreType','Assortment','PromoInterval'],axis='columns')

dfTrain=dfTrain.drop(['ST4','AT3','PI4'],axis='columns')

dfTrain['StateHoliday'] = dfTrain['StateHoliday'].astype(str)

dummies_stateHoliday=pd.get_dummies(dfTrain['StateHoliday'])

dfTrain=pd.concat([dfTrain,dummies_stateHoliday],axis='columns')

dfTrain = dfTrain.rename({'0': 'SH11', 'a': 'SH2','b':'SH3','c':'SH4'}, axis=1) 

dfTrain=dfTrain.drop(['StateHoliday'],axis='columns')

dfTrain=dfTrain.drop(['SH4'],axis='columns')

'''

In [8]:
dfTrain.head()

Store  DayOfWeek   Date  Sales  Customers  ...  PI2  PI3  SH11  SH2  SH3
0      1          5  16647   5263        555  ...    0    0     1    0    0
1      2          5  16647   6064        625  ...    1    0     1    0    0
2      3          5  16647   8314        821  ...    1    0     1    0    0
3      4          5  16647  13995       1498  ...    0    0     1    0    0
4      5          5  16647   4822        559  ...    0    0     1    0    0

[5 rows x 25 columns]

In [0]:
#dfTrain.to_csv('/content/grdive/My Drive/Rossman Machine Learning/CompleteDataFinal.csv')

In [0]:
'''
dfTrain['Date']=pd.to_datetime(dfTrain['Date'])
dfTrain['Date']=dfTrain['Date']-datetime.datetime(1970,1,1)
dfTrain['Date']=dfTrain['Date'].dt.days
'''

In [0]:
X=pd.concat([dfTrain.iloc[:,0:3],dfTrain.iloc[:,4:25]],axis='columns').values
y=dfTrain.iloc[:,3].values

In [0]:
X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.2,random_state=0)

In [11]:
len(X)

1017209

In [0]:
sc_X=StandardScaler()
X_train=sc_X.fit_transform(X_train)
X_test=sc_X.transform(X_test)

In [14]:
print(X_train.shape)
print(X_test.shape)
print(y_train.shape)
print(y_test.shape)

(813767, 24)
(203442, 24)
(813767,)
(203442,)


In [0]:
#Statistic correlations
X=np.append(arr=np.ones((1017209,1)).astype(int),values=X,axis=1)

In [0]:
X_opt=X[:,[0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23,24]]

In [17]:
regressor_OLS=sm.OLS(endog=y,exog=X_opt).fit()
regressor_OLS.summary()

<class 'statsmodels.iolib.summary.Summary'>
"""
                            OLS Regression Results                            
==============================================================================
Dep. Variable:                      y   R-squared:                       0.854
Model:                            OLS   Adj. R-squared:                  0.854
Method:                 Least Squares   F-statistic:                 2.715e+05
Date:                Fri, 05 Jul 2019   Prob (F-statistic):               0.00
Time:                        22:50:28   Log-Likelihood:            -8.8610e+06
No. Observations:             1017209   AIC:                         1.772e+07
Df Residuals:                 1017186   BIC:                         1.772e+07
Df Model:                          22                                         
Covariance Type:            nonrobust                                         
==============================================================================
                 coef    std err          t      P>|t|      [0.025      0.975]
------------------------------------------------------------------------------
const      -6488.0147     89.362    -72.604      0.000   -6663.160   -6312.869
x1            -0.1843      0.005    -39.662      0.000      -0.193      -0.175
x2           -77.6642      0.953    -81.509      0.000     -79.532     -75.797
x3             0.4202      0.005     79.168      0.000       0.410       0.431
x4             6.0493      0.004   1488.980      0.000       6.041       6.057
x5          1492.1079      5.912    252.393      0.000    1480.521    1503.695
x6          1283.6398      3.329    385.548      0.000    1277.114    1290.165
x7            62.7847      3.978     15.783      0.000      54.988      70.581
x8             0.0146      0.002      7.602      0.000       0.011       0.018
x9            39.6737      7.077      5.606      0.000      25.803      53.544
x10           -0.0916      0.038     -2.401      0.016      -0.166      -0.017
x11         3.794e+05   4.23e+04      8.976      0.000    2.97e+05    4.62e+05
x12           25.4951      2.504     10.181      0.000      20.587      30.403
x13         -251.9129     28.024     -8.989      0.000    -306.839    -196.986
x14         -153.8173     22.084     -6.965      0.000    -197.101    -110.534
x15         -718.2049     37.122    -19.347      0.000    -790.962    -645.448
x16          297.8148     49.017      6.076      0.000     201.743     393.886
x17         -692.9613     42.929    -16.142      0.000    -777.102    -608.821
x18          118.7540     27.477      4.322      0.000      64.899     172.608
x19         1.262e+05   1.41e+04      8.972      0.000    9.86e+04    1.54e+05
x20         1.264e+05   1.41e+04      8.971      0.000    9.88e+04    1.54e+05
x21         1.268e+05   1.41e+04      8.986      0.000    9.91e+04    1.54e+05
x22          340.2846     23.678     14.371      0.000     293.876     386.693
x23         -445.6726     25.360    -17.574      0.000    -495.378    -395.967
x24         -703.5562     29.182    -24.109      0.000    -760.753    -646.360
==============================================================================
Omnibus:                   189008.080   Durbin-Watson:                   1.780
Prob(Omnibus):                  0.000   Jarque-Bera (JB):          3748130.139
Skew:                           0.344   Prob(JB):                         0.00
Kurtosis:                      12.379   Cond. No.                     3.10e+20
==============================================================================

Warnings:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.
[2] The smallest eigenvalue is 2.78e-27. This might indicate that there are
strong multicollinearity problems or that the design matrix is singular.
"""

In [0]:
#Multiple Linear Regression
regressor=LinearRegression()

In [19]:
regressor.fit(X_train,y_train)

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=None, normalize=False)

In [0]:
y_pred=regressor.predict(X_test)

In [21]:
print(y_pred)

[ 7166.14629984 12432.61895609  8796.24395609 ...  6113.74786234
  6478.36504984  3239.17754984]


In [22]:
print(y_test)

[7285 6221 8132 ... 6191 5663 2698]


In [23]:
#Decision Tree
regressor=DecisionTreeRegressor(random_state=0)
regressor.fit(X_train,y_train)

DecisionTreeRegressor(criterion='mse', max_depth=None, max_features=None,
                      max_leaf_nodes=None, min_impurity_decrease=0.0,
                      min_impurity_split=None, min_samples_leaf=1,
                      min_samples_split=2, min_weight_fraction_leaf=0.0,
                      presort=False, random_state=0, splitter='best')

In [0]:
y_pred_decisionTree=regressor.predict(X_test)

In [26]:
print(y_pred_decisionTree)
print(y_test)

[7606. 6982. 7571. ... 6664. 5358. 1919.]
[7285 6221 8132 ... 6191 5663 2698]


In [0]:
#Random Forest
regressor=RandomForestRegressor(n_estimators=10,random_state=0)

In [29]:
regressor.fit(X_train,y_train)

RandomForestRegressor(bootstrap=True, criterion='mse', max_depth=None,
                      max_features='auto', max_leaf_nodes=None,
                      min_impurity_decrease=0.0, min_impurity_split=None,
                      min_samples_leaf=1, min_samples_split=2,
                      min_weight_fraction_leaf=0.0, n_estimators=10,
                      n_jobs=None, oob_score=False, random_state=0, verbose=0,
                      warm_start=False)

In [0]:
y_pred_randomForest=regressor.predict(X_test)

In [31]:
print(y_pred_randomForest)
print(y_test)

[8422.1 6973.1 7699.  ... 6784.3 5379.1 2009.9]
[7285 6221 8132 ... 6191 5663 2698]


In [38]:
#(np.sum((y_pred_randomForest[:]-y_test[:])**2))/len(y_test)

673870.1093687635

In [37]:
10/3

3.3333333333333335